import { BeforeAll, AfterAll, Before, After, setDefaultTimeout } from '@cucumber/cucumber';
import { configure, Cast, actorCalled } from '@serenity-js/core';
import { BrowseTheWebWithPlaywright } from '@serenity-js/playwright';
import * as playwright from 'playwright';
import { spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { log } from '../../src/utils/loggers/logger';
import { ensureDirectoryExist } from '../../src/utils/helpers/createDirectory';
import { ENV } from '../../src/utils/helpers/environment.helper';
import { APP_CONSTANTS } from '../../src/utils/helpers/constants.helper';
import { Login } from '../../src/screenplay/tasks/login/login-task';
import { Navigate } from '@serenity-js/web';
import { Ensure, equals } from '@serenity-js/assertions';
import { DashboardIsVisible } from '../../src/screenplay/question/login/login';

/**
* Global configuration of Serenity/JS and Cucumber
* Encapsulates all variables and test configuration logic
 */
(() => {

    // ENVIRONMENTS GLOBALS
    let browser: playwright.Browser;
    const PATHS = {
        screenshots: path.resolve('./target/screenshots'),
        serenityOutput: path.resolve('./target/site/serenity'),
    } as const;
    const SCREENSHOT_PATTERN = /^(Photo|Screenshot|.*Feature.*|.*Scenario.*).*\.png$/i;

 
    // INITIAL CONFIGURATION
    setDefaultTimeout(APP_CONSTANTS.TIMEOUT);


    // ASSISTANTS FUNCTIONS
    /**
     * Move the screenshots generated by Serenity to the screenshots folder.
     */
    function moveScreenshots(): void {
        const files = fs.readdirSync(PATHS.serenityOutput);

        for (const file of files) {
            if (SCREENSHOT_PATTERN.test(file)) {
                const src = path.join(PATHS.serenityOutput, file);
                const dest = path.join(PATHS.screenshots, file);

                if (fs.existsSync(src)) {
                    fs.renameSync(src, dest);
                }
            }
        }
    }

    /**
     * Generate the Serenity BDD HTML report
     * @returns true if the report was generated successfully, false otherwise
     */
    function generateSerenityReport(): boolean {
        const result = spawnSync('npx', [
            'serenity-bdd',
            'run',
            `--outputDirectory=${PATHS.serenityOutput}`,
        ], { stdio: 'inherit', shell: true });

        return result.status === 0;
    }

    /**
     * Configure the browser with the necessary options.
     */
    async function setupBrowser(): Promise<void> {
        browser = await playwright.chromium.launch({
            headless: ENV.IS_HEADLESS,
            slowMo: APP_CONSTANTS.SLOW_MOTION || 0,
            args: [
                '--start-maximized',
                '--disable-blink-features=AutomationControlled',
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--disable-gpu',
                '--disable-features=TranslateUI',
            ],
        });
    }

    /**
     * Set up Serenity/JS with the actors and crew
     */
    function configureSerenity(): void {
        configure({
            actors: Cast.where(actor =>
                actor.whoCan(
                    BrowseTheWebWithPlaywright.using(browser, {
                        baseURL: ENV.ADDRESS_URL,
                        viewport: null
                    }),
                )
            ),

            crew: [
                '@serenity-js/console-reporter',

                ['@serenity-js/serenity-bdd', {
                    specDirectory: './tests'
                }],

                ['@serenity-js/core:ArtifactArchiver', {
                    outputDirectory: PATHS.serenityOutput
                }],

                ['@serenity-js/web:Photographer', {
                    strategy: 'TakePhotosOfFailures',
                    photoStoragePath: PATHS.screenshots
                }]
            ]
        });
    }

    /**
     * BeforeAll Hook
     * Runs once before all scenarios
     * - Configures the browser
     * - Creates the necessary directories
     * - Configures Serenity/JS
     */
    BeforeAll(async () => {
        log.info('Starting general settings ⚙️');

        await setupBrowser();

        ensureDirectoryExist(PATHS.serenityOutput, 'Serenity output');
        ensureDirectoryExist(PATHS.screenshots, 'Screenshots');

        configureSerenity();

        log.info('Configuration completed successfully 🆗');
    });

     /**
     * Before Hook
     * Runs before each scenario (except those marked with @LOGIN)
     * - Performs automatic login
     * - Verifies that the dashboard is visible
     */

    Before({ tags: 'not @LOGIN' }, async ({ pickle }) => {
        log.info(`Running scenario: ${pickle.name} 🚀`);

        await actorCalled("Tester").attemptsTo(
            Navigate.to("/#home-page"),
            Login.toLogInWithValidCredentials(ENV.USER_MAIL, ENV.PASSWORD),
            Ensure.that(DashboardIsVisible(), equals(true))
        );
    });

    /**
     * After Hook
     * Runs after each scenario
     * - Records the scenario result
     */
    After(async ({ pickle, result }) => {
        const status = result?.status || 'UNKNOWN';
        const emoji = status === 'PASSED' ? '✅' : '❌';

        log.info(`${emoji} Scenario: ${pickle.name} completed with status: ${status}`);
    });

    /**
     * AfterAll Hook
     * Runs once after all scenarios
     * - Moves screenshots to their folder
     * - Generates the Serenity HTML report
     * - Closes the browser
     */

    AfterAll(async () => {
        log.info('Starting cleanup and report generation 🔄️');

        try {
            // Move screenshots
            moveScreenshots();

            // Report generate
            const reportGenerated = generateSerenityReport();

            if (reportGenerated) {
                log.info('Serenity report generated successfully ✅');
            } else {
                log.error('Error generating the Serenity BDD report ❌');
            }

            // Browser closed
            if (browser) {
                await browser.close();
                log.info('Browser closed successfully 🆗');
            }

        } catch (error) {
            log.error(`Error during cleanup: ${error}`);
            throw error;
        }
    });

})();